// AI Lingo — 81 terms across 5 journeys. Text verbatim from the catalog.
const T = (id, line, t, pos, pr, d, u, rel) => ({ id, line, t, pos, pr, d, u, rel: rel || [] });

export const LINES = [
  { n: 1, name: "Foundations", journey: "Understanding AI", q: "What is this stuff everyone's talking about?", blurb: "The shared vocabulary everyone needs before any hands-on work.", c: "#1338b0" },
  { n: 2, name: "Everyday Use", journey: "Using AI", q: "How do I work with these tools day to day?", blurb: "The practical vocabulary of a hands-on user.", c: "#cc3311" },
  { n: 3, name: "Evaluation", journey: "Evaluating AI", q: "How do I judge claims, vendors, and models?", blurb: "The vocabulary of an informed buyer and skeptical reader.", c: "#007a5e" },
  { n: 4, name: "Implementation", journey: "Deploying AI", q: "How does this actually get built into our work?", blurb: "The vocabulary of implementation conversations.", c: "#7b2fbe" },
  { n: 5, name: "Governance", journey: "Governing AI", q: "How do we keep this safe, fair, and accountable?", blurb: "The vocabulary of oversight and risk.", c: "#c98200" }
];

export const TERMS = [
  T("ai", 1, "Artificial Intelligence (AI)", "noun", "ar-tih-FISH-ul in-TEL-ih-jens",
    "The field of computer science focused on building systems that perform tasks normally requiring human intelligence, such as understanding language, recognizing images, making predictions, and solving problems.",
    "Our modernization strategy treats artificial intelligence as a tool to augment analysts, not replace them.", ["ml", "algorithm", "agi"]),
  T("ml", 1, "Machine Learning (ML)", "noun", "muh-SHEEN LUR-ning",
    "A subset of AI in which systems learn patterns from data rather than following rules a programmer wrote by hand. The more representative the data, the better the system performs.",
    "The fraud detection team uses machine learning to flag unusual transactions that rule-based systems would miss.", ["training-data", "supervised", "deep-learning"]),
  T("model", 1, "Model", "noun", "MAH-dul",
    "The trained artifact at the center of any AI system: a program that has learned patterns from data and can now make predictions or generate content. When people say \u201cthe model,\u201d they mean the thing that actually does the work.",
    "We evaluated three different models before selecting one accurate enough for production use.", ["weights", "parameters", "foundation-model"]),
  T("algorithm", 1, "Algorithm", "noun", "AL-guh-rith-um",
    "A step-by-step procedure a computer follows to solve a problem or complete a task. Every model is built and run by algorithms, but not every algorithm involves AI.",
    "The sorting feature is just a simple algorithm; there is no AI involved in that part of the tool.", ["ai", "automation"]),
  T("automation", 1, "Automation", "noun", "aw-tuh-MAY-shun",
    "Using technology to perform tasks with minimal human intervention. AI expands what can be automated from repetitive, rule-based work into tasks requiring judgment and language.",
    "We automated the intake form processing first because it was high volume and low risk.", ["workflow", "agent"]),
  T("genai", 1, "Generative AI", "noun", "JEN-er-uh-tiv AY-EYE",
    "AI that creates new content, such as text, images, audio, or code, rather than simply classifying or ranking existing information. Chatbots, image generators, and coding assistants are all generative AI.",
    "Generative AI drafted the first version of the report, and the analyst refined it from there.", ["llm", "chatbot"]),
  T("llm", 1, "Large Language Model (LLM)", "noun", "larj LANG-gwij MAH-dul",
    "A type of generative AI trained on enormous amounts of text, enabling it to understand and produce human language. LLMs power most modern chatbots and AI assistants.",
    "The vendor's product is built on a large language model, so it can summarize documents and answer questions in plain English.", ["genai", "nlp", "transformer"]),
  T("nlp", 1, "Natural Language Processing (NLP)", "noun", "NACH-er-ul LANG-gwij PRAH-ses-ing",
    "The branch of AI concerned with enabling computers to read, understand, and produce human language. LLMs are the most powerful NLP technology to date, but NLP also includes older tools like spam filters and translation software.",
    "Before LLMs, our natural language processing pipeline could tag documents but could not summarize them.", ["llm", "embeddings"]),
  T("cv", 1, "Computer Vision", "noun", "kum-PYOO-ter VIZH-un",
    "The branch of AI that enables machines to interpret images and video: recognizing objects, reading text in photos, or detecting changes in imagery.",
    "The inspection team uses computer vision to spot corrosion in drone footage of the towers.", ["multimodal", "deep-learning"]),
  T("multimodal", 1, "Multimodal", "adjective", "mul-tee-MOH-dul",
    "Able to work with more than one type of input or output, such as text, images, audio, and video. A multimodal model can look at a chart and describe it in words.",
    "Because the assistant is multimodal, she photographed the whiteboard and asked it to turn the diagram into meeting notes.", ["cv", "llm"]),
  T("nn", 1, "Neural Network", "noun", "NUR-ul NET-wurk",
    "A computing architecture loosely inspired by the human brain, made of layers of interconnected nodes that pass signals to one another. Neural networks are the machinery underneath modern AI.",
    "The presenter explained that the model is a neural network with billions of connections, not a database of stored answers.", ["deep-learning", "parameters", "transformer"]),
  T("deep-learning", 1, "Deep Learning", "noun", "DEEP LUR-ning",
    "Machine learning that uses neural networks with many layers (\u201cdeep\u201d refers to the number of layers). Deep learning drove the breakthroughs of the last decade in vision, speech, and language.",
    "Deep learning made speech-to-text accurate enough that we finally retired the manual transcription contract.", ["nn", "ml"]),
  T("training-data", 1, "Training Data", "noun", "TRAY-ning DAY-tuh",
    "The examples a model learns from during its creation. A model's strengths, blind spots, and biases all trace back to its training data.",
    "The model struggles with our acronyms because our internal documents were never part of its training data.", ["bias", "synthetic-data", "cutoff"]),
  T("parameters", 1, "Parameters", "noun", "puh-RAM-ih-turz",
    "The internal numerical values a model adjusts as it learns. Modern LLMs have billions of parameters, which is why you hear model sizes described as \u201c7 billion\u201d or \u201c70 billion.\u201d",
    "The briefing compared a small model with 8 billion parameters against a frontier model many times that size.", ["weights", "quantization"]),
  T("weights", 1, "Model Weights", "noun", "MAH-dul WAYTS",
    "The final, learned values of a model's parameters after training. The weights effectively are the model: whoever has the weights can run the model.",
    "Releasing the model weights means anyone can download and run the model on their own hardware.", ["parameters", "open-weight"]),
  T("agi", 1, "AGI (Artificial General Intelligence)", "noun", "ay-jee-EYE",
    "A hypothetical future AI capable of matching or exceeding human performance across most intellectual tasks, not just narrow ones. AGI does not currently exist; treat headlines about it as speculation about the future, not description of the present.",
    "The keynote speculated about AGI, but every product on the show floor was narrow, task-specific AI.", ["ai", "frontier", "emergent"]),

  T("chatbot", 2, "Chatbot", "noun", "CHAT-baht",
    "A software application you interact with through conversation, by typing or speaking. Modern chatbots are powered by LLMs and can handle open-ended questions rather than scripted menus.",
    "The HR chatbot answered her benefits question in seconds instead of a two-day email turnaround.", ["copilot", "agent"]),
  T("copilot", 2, "Copilot / AI Assistant", "noun", "KOH-py-lut",
    "An AI tool embedded in your workflow that helps you complete tasks: drafting documents, summarizing meetings, writing formulas, or suggesting code. The name signals the intended relationship: the human flies the plane.",
    "He uses the AI assistant to draft responses, but he reviews every message before it goes out.", ["chatbot", "hitl"]),
  T("prompt", 2, "Prompt", "noun, verb", "prahmpt",
    "The input you give an AI model: your question, instruction, or request. As a verb, the act of writing that input. The quality of the prompt strongly shapes the quality of the response.",
    "She rewrote her prompt to include the audience and desired length, and the draft improved immediately.", ["system-prompt", "prompt-eng", "steering"]),
  T("system-prompt", 2, "System Prompt", "noun", "SIS-tem prahmpt",
    "A standing set of instructions given to a model before the user ever types anything, defining its role, tone, rules, and boundaries. Users usually never see it, but it shapes every response.",
    "The tool refuses to discuss pricing because its system prompt instructs it to route those questions to sales.", ["prompt", "steering", "guardrails"]),
  T("prompt-eng", 2, "Prompt Engineering", "noun", "prahmpt en-jih-NEER-ing",
    "The practice of crafting and refining prompts to get reliably better results from a model: providing context, examples, constraints, and structure.",
    "A half day of prompt engineering turned an unreliable summarization tool into one the team actually trusts.", ["prompt", "few-shot", "context-eng"]),
  T("steering", 2, "Steering", "noun, verb", "STEER-ing",
    "Guiding a model's behavior toward the outputs you want through instructions, examples, tone, constraints, and settings. Steering is the working skill underneath prompt engineering: less about magic words, more about giving clear direction.",
    "A single line of steering in the system prompt, requiring a policy citation for every claim, fixed most of the quality complaints.", ["prompt-eng", "system-prompt"]),
  T("context-eng", 2, "Context Engineering", "noun", "KAHN-tekst en-jih-NEER-ing",
    "The discipline of managing everything a model sees at once: instructions, documents, retrieved data, conversation history, and tool outputs, all within the context window. The emerging successor to prompt engineering, reflecting that modern AI work is less about wording a single request and more about curating what the model knows when it answers.",
    "Prompt tweaks stopped helping; the real fix was context engineering, deciding which documents and history the assistant loads for each task.", ["context-window", "rag", "prompt-eng"]),
  T("token", 2, "Token", "noun", "TOH-ken",
    "The unit of text a model actually reads and writes, roughly three-quarters of a word in English. Models measure input, output, cost, and limits in tokens, not words or pages.",
    "The API bills per token, so the team trimmed boilerplate from their prompts to cut costs.", ["context-window", "inference"]),
  T("context-window", 2, "Context Window", "noun", "KAHN-tekst WIN-doh",
    "The maximum amount of text (measured in tokens) a model can consider at once: your conversation, any documents you share, and its own responses. Information that falls outside the window is invisible to the model.",
    "The contract would not fit in the context window, so she analyzed it section by section.", ["token", "context-eng"]),
  T("cutoff", 2, "Knowledge Cutoff", "noun", "NAH-lij KUT-awf",
    "The date after which a model's training data ends. Without live search or retrieval, a model knows nothing about events after its cutoff, no matter how confidently it answers.",
    "The model gave an outdated org chart because the reorganization happened after its knowledge cutoff.", ["training-data", "rag", "hallucination"]),
  T("hallucination", 2, "Hallucination", "noun", "huh-loo-sih-NAY-shun",
    "When a model generates information that is fluent and confident but false: invented citations, fabricated statistics, or plausible-sounding facts that do not exist. The single most important limitation for users to internalize.",
    "The brief cited a regulation that turned out to be a hallucination, which is why every citation now gets verified.", ["grounding", "cutoff", "rag"]),
  T("few-shot", 2, "Zero-Shot / Few-Shot Learning", "noun", "ZEER-oh shaht, FYOO shaht",
    "Zero-shot: asking a model to perform a task with no examples, just instructions. Few-shot: including a handful of examples in your prompt to show the model the pattern you want. Few-shot prompting often dramatically improves consistency.",
    "Zero-shot results were hit or miss, but pasting three example entries into the prompt made the formatting perfect every time.", ["prompt-eng", "fine-tuning"]),
  T("stochastic", 2, "Stochastic", "adjective", "stuh-KAS-tik",
    "Involving randomness. LLMs are stochastic by design: they select each next token from a range of probable options rather than always choosing the single most likely one, which is why the same prompt can produce different answers.",
    "The output varies between runs because the model is stochastic, not because anything is broken.", ["deterministic", "temperature", "top-p"]),
  T("deterministic", 2, "Deterministic", "adjective", "dih-tur-mih-NIS-tik",
    "Producing the same output every time for the same input. Traditional software is deterministic; LLMs generally are not, though settings can push them closer to it.",
    "The audit tool must be deterministic, so we use a fixed calculation there instead of a language model.", ["stochastic", "temperature"]),
  T("temperature", 2, "Temperature", "noun", "TEM-per-uh-chur",
    "A setting that controls how much randomness a model uses when choosing its next token. Low temperature makes output more focused and repeatable; high temperature makes it more varied and creative.",
    "They lowered the temperature for the compliance summaries and raised it for the brainstorming assistant.", ["top-p", "stochastic"]),
  T("top-p", 2, "Top-P", "noun", "tahp-PEE",
    "A sampling setting that limits the model's word choices to the smallest set of options whose combined probability reaches a threshold P. Like temperature, it trades consistency against variety; the two are usually tuned together.",
    "The vendor recommended adjusting either temperature or top-p, but not both at once.", ["temperature", "stochastic"]),
  T("enterprise", 2, "Enterprise vs. Consumer AI", "noun", "EN-ter-pryz vs. kun-SOO-mer AY-EYE",
    "The distinction between AI products governed by an organizational agreement (with data protections, admin controls, and audit capability) and free public tools with no such guarantees. The same brand name can exist in both forms with very different rules.",
    "Pasting case notes into the consumer version is prohibited; the enterprise deployment is approved because our data is not used for training.", ["pii", "aup"]),
  T("pii", 2, "Data Privacy / PII", "noun", "pee-eye-EYE",
    "Personally Identifiable Information: names, ID numbers, contact details, and any data that can identify an individual. The operational rule for AI tools: know where your input goes before you type it, and never enter PII into unapproved tools.",
    "The training's first rule was simple: no PII in any AI tool that has not been approved for it.", ["enterprise", "aup", "governance"]),
  T("aup", 2, "Acceptable Use Policy (AUP)", "noun", "ay-yoo-PEE",
    "The organizational policy defining which AI tools are approved, what data may be used with them, and what uses are prohibited. If you have not read yours, that is the actual first step in AI adoption.",
    "Before piloting the new assistant, the team checked the AUP to confirm document uploads were permitted.", ["governance", "pii"]),

  T("foundation-model", 3, "Foundation Model", "noun", "fown-DAY-shun MAH-dul",
    "A large, general-purpose model trained on broad data that serves as the base for many downstream applications. Most AI products you encounter are built on top of someone else's foundation model.",
    "The startup did not build its own AI; it built a specialized product on top of an existing foundation model.", ["model", "frontier", "fine-tuning"]),
  T("frontier", 3, "Frontier", "adjective, noun", "frun-TEER",
    "Describing the most capable models currently in existence, or the small set of labs that produce them. \u201cFrontier model\u201d signals state of the art; \u201cfrontier lab\u201d refers to the organizations pushing that edge.",
    "The task only needed a small, cheap model, not a frontier model, so the projected costs dropped by 90 percent.", ["foundation-model", "benchmark"]),
  T("open-weight", 3, "Open Weight", "adjective", "OH-pen WAYT",
    "Describing a model whose weights are publicly downloadable, allowing anyone to run, inspect, or fine-tune it on their own infrastructure. Distinct from fully open source, since the training data and code often remain private.",
    "They chose an open weight model so sensitive data could stay entirely on agency servers.", ["weights", "open-source"]),
  T("open-source", 3, "Open Source vs. Closed Source Models", "noun", "OH-pen sors vs. KLOHZD sors",
    "The spectrum of model availability. Closed source: accessible only through the provider's service, internals private. Truly open source: weights, code, and training details all public. Most \u201copen\u201d models are actually open weight, somewhere in between.",
    "The evaluation compared a closed source model accessed by API against an open source alternative they could host themselves.", ["open-weight", "api"]),
  T("model-card", 3, "Model Card", "noun", "MAH-dul kard",
    "A standardized document describing a model: what it was trained on, what it is intended for, how it was evaluated, and its known limitations. The AI equivalent of a nutrition label, and a reasonable thing to request from any vendor.",
    "Ask for the model card before the demo; the limitations section tells you more than the sales deck.", ["benchmark", "governance"]),
  T("benchmark", 3, "Benchmark", "noun", "BENCH-mark",
    "A standardized test used to measure and compare model performance on tasks like reasoning, coding, or reading comprehension. Useful signals, but vendors choose which benchmarks to publish, and high scores do not guarantee performance on your tasks.",
    "It topped the public benchmarks but failed on our documents, which is why we always run our own evaluation.", ["model-card", "frontier"]),
  T("supervised", 3, "Supervised Learning", "noun", "SOO-per-vyzd LUR-ning",
    "Training a model on labeled examples, where each input comes paired with the correct answer. Powers most classification and prediction systems: spam filters, document routing, risk scoring.",
    "The intake classifier was built with supervised learning on ten thousand hand-labeled requests.", ["unsupervised", "ml"]),
  T("unsupervised", 3, "Unsupervised Learning", "noun", "un-SOO-per-vyzd LUR-ning",
    "Training a model on data without labels, letting it discover patterns, clusters, and structure on its own. Useful when you do not know in advance what categories exist.",
    "Unsupervised learning surfaced five distinct customer complaint clusters nobody had defined beforehand.", ["supervised", "embeddings"]),
  T("rl", 3, "Reinforcement Learning", "noun", "ree-in-FORS-ment LUR-ning",
    "Training a model through trial, error, and reward signals rather than labeled examples: the system learns which behaviors earn rewards and repeats them. The technique behind game-playing AI and a key ingredient in training modern assistants.",
    "Reinforcement learning is how the system learned strategy: millions of games against itself, learning from wins and losses.", ["rlhf", "alignment"]),
  T("rlhf", 3, "RLHF (Reinforcement Learning from Human Feedback)", "noun", "ar-el-aych-EF",
    "A training stage where humans rank model responses and the model learns to prefer what humans rated highly. RLHF is a major reason modern chatbots feel helpful and polite rather than raw and erratic.",
    "The base model was capable but blunt; RLHF is what shaped it into a usable assistant.", ["rl", "alignment"]),
  T("fine-tuning", 3, "Fine-Tuning", "noun, verb", "FYN-TOO-ning",
    "Additional training that adapts an existing model to a specific domain, task, or style using a smaller, targeted dataset. When a vendor says \u201ctrained on your data,\u201d they usually mean fine-tuning, not building from scratch.",
    "Fine-tuning on two years of correspondence taught the model our terminology and house style.", ["foundation-model", "distillation"]),
  T("synthetic-data", 3, "Synthetic Data", "noun", "sin-THET-ik DAY-tuh",
    "Artificially generated data used for training or testing, often created by another AI model. Valuable when real data is scarce, sensitive, or expensive, but quality and realism vary.",
    "They used synthetic data to test the system because regulations barred using real patient records.", ["training-data", "deepfake"]),
  T("distillation", 3, "Distillation", "noun", "dis-tih-LAY-shun",
    "Training a smaller, cheaper model to imitate a larger one, transferring much of the capability at a fraction of the size and cost. A common way efficient models are produced.",
    "The mobile version was created through distillation, shrinking the flagship model to run on a phone.", ["quantization", "fine-tuning"]),
  T("emergent", 3, "Emergent Behavior", "noun", "ee-MUR-jent bee-HAYV-yur",
    "Capabilities that appear in larger models without being explicitly trained, seemingly arising from scale itself. A reminder that model capabilities are discovered as much as designed, which matters for risk assessment.",
    "Nobody trained it to do arithmetic; that was emergent behavior that showed up as the models grew.", ["agi", "red-teaming"]),
  T("cot", 3, "Chain-of-Thought / Reasoning Models", "noun", "CHAYN uv THAWT",
    "Chain-of-thought: prompting or training a model to work through problems step by step rather than jumping to an answer. Reasoning models build this in, spending extra \u201cthinking\u201d time before responding, trading speed and cost for accuracy on hard problems.",
    "For the routine lookups they use a fast model, but the policy analysis goes to a reasoning model that works through the logic step by step.", ["latency", "orchestration"]),

  T("api", 4, "API (Application Programming Interface)", "noun", "ay-pee-EYE",
    "The standard way software systems talk to each other. When teams \u201caccess the model via API,\u201d they mean their applications send requests to the model over the internet and receive responses, no chatbot interface involved.",
    "The case management system calls the model through an API, so users never leave the tool they already know.", ["inference", "mcp"]),
  T("inference", 4, "Inference", "noun", "IN-fer-ens",
    "Running a trained model to produce output: every question answered, every document summarized. Training happens once; inference happens every time anyone uses the model, which is why inference costs dominate budgets at scale.",
    "Training was the vendor's expense; inference is ours, billed on every request our users make.", ["compute", "token", "latency"]),
  T("compute", 4, "Compute / GPU", "noun", "kum-PYOOT, jee-pee-YOO",
    "Compute: the processing power required to train and run AI. GPU (graphics processing unit): the specialized chip that provides most of it. Compute is the scarce, expensive resource behind nearly every AI cost and capacity conversation.",
    "The project stalled not on talent but on compute; GPU capacity was booked out for months.", ["inference", "quantization"]),
  T("latency", 4, "Latency vs. Throughput", "noun", "LAY-ten-see, THROO-puut",
    "Latency: how long one request takes to get a response. Throughput: how many requests a system can handle over time. Interactive tools need low latency; batch processing needs high throughput; architectures optimize for one or the other.",
    "The chatbot needs sub-second latency, but the overnight document pipeline just needs enough throughput to finish by morning.", ["inference", "cot"]),
  T("quantization", 4, "Quantization", "noun", "kwahn-tih-ZAY-shun",
    "Compressing a model by storing its weights at lower numerical precision, making it smaller, faster, and cheaper to run with a modest accuracy cost. How large models get squeezed onto ordinary hardware.",
    "After quantization, the model ran on a standard laptop instead of requiring a GPU server.", ["weights", "distillation"]),
  T("embeddings", 4, "Embeddings", "noun", "em-BED-ingz",
    "Numerical representations of text (or images, or audio) that capture meaning, letting computers measure how similar two pieces of content are. The technology behind semantic search: finding documents by meaning rather than keyword.",
    "Embeddings let the search tool find the relevant memo even though it never used the exact words in her query.", ["rag", "nlp"]),
  T("transformer", 4, "Transformer Architecture", "noun", "tranz-FOR-mer AR-kih-tek-chur",
    "The neural network design, introduced in 2017, that underpins modern LLMs (the \u201cT\u201d in GPT). Its key innovation is processing all parts of an input in relation to each other simultaneously, which made today's language capabilities possible.",
    "Every major language model on the market today descends from the transformer architecture.", ["attention", "nn", "llm"]),
  T("attention", 4, "Attention Mechanism", "noun", "uh-TEN-shun MEK-uh-niz-um",
    "The core component of the transformer that lets a model weigh which parts of the input matter most for each part of the output, such as connecting a pronoun to the name it refers to paragraphs earlier.",
    "The attention mechanism is how the model tracks that \u201cthe contractor\u201d in paragraph nine refers to the firm named on page one.", ["transformer"]),
  T("rag", 4, "Retrieval-Augmented Generation (RAG)", "noun", "rag",
    "An architecture where the system first retrieves relevant documents from your own knowledge base, then has the model generate an answer using them. The standard pattern for making AI answer from your content rather than only its training data.",
    "The policy assistant uses RAG, so its answers come from our current manuals instead of the model's memory.", ["grounding", "embeddings", "hallucination"]),
  T("grounding", 4, "Grounding", "noun, verb", "GROWN-ding",
    "Connecting a model's output to verifiable sources: retrieved documents, live data, or citations. Grounded systems can show their work; ungrounded ones rely on training memory. Grounding is the primary defense against hallucination.",
    "Every answer is grounded in a cited document, so reviewers can verify claims in one click.", ["hallucination", "rag", "interpretability"]),
  T("tool-use", 4, "Tool Use / Function Calling", "noun", "TOOL yooss",
    "The capability that lets a model invoke external software during a conversation: searching the web, querying a database, sending an email, running a calculation. Tool use is what turns a model that talks into a system that acts.",
    "With tool use enabled, the assistant does not just draft the summary; it pulls the actual figures from the finance system first.", ["agent", "mcp"]),
  T("agent", 4, "Agent", "noun", "AY-jent",
    "An AI system that can take actions on its own to accomplish a goal: it observes a situation, decides what to do, uses tools to do it, and checks the result. A chatbot answers; an agent acts.",
    "Instead of just drafting the reply, the agent looked up the account status, wrote the response, and queued it for approval.", ["agentic", "workflow", "tool-use"]),
  T("workflow", 4, "Workflow", "noun", "WURK-floh",
    "A defined sequence of steps that accomplishes a task, with AI handling some or all of the steps in a fixed order. Workflows follow a script; agents decide dynamically. Most reliable AI deployments today are workflows, not agents.",
    "The intake workflow runs the same five steps every time: extract, classify, summarize, route, notify.", ["agent", "orchestration"]),
  T("agentic", 4, "Agentic AI / AI Agents", "noun", "ay-JEN-tik AY-EYE",
    "The design approach in which AI agents pursue multi-step goals with autonomy: planning, using tools, checking results, and adjusting along the way rather than following a fixed script. The current frontier of AI products, and where oversight questions get most serious.",
    "The agent booked the travel end to end: it compared fares, checked the policy limits, and filed the approval request.", ["agent", "hitl", "guardrails"]),
  T("orchestration", 4, "Orchestration", "noun", "or-kes-TRAY-shun",
    "Coordinating multiple models, tools, and workflow steps into one coherent system: deciding which model handles which task, in what order, with what handoffs. As deployments mature, the orchestration layer becomes where the real engineering lives.",
    "One cheap model triages the requests, a reasoning model handles the hard ones, and the orchestration layer routes between them.", ["workflow", "cot"]),
  T("mcp", 4, "MCP (Model Context Protocol)", "noun", "em-see-PEE",
    "An open standard for connecting AI models to external tools, systems, and data sources. Before MCP, every model-to-tool connection was custom; MCP standardizes it, like USB did for device connections.",
    "Because both vendors support MCP, the assistant connects to our document system without custom integration work.", ["mcp-server", "tool-use"]),
  T("mcp-server", 4, "MCP Server", "noun", "em-see-PEE SUR-ver",
    "A program that exposes a specific system's capabilities (a database, a ticketing tool, a file store) to AI models through the MCP standard. Each server is a doorway between the model and one of your systems.",
    "IT stood up an MCP server for the ticketing system, so the assistant can now look up and update tickets directly.", ["mcp", "mcp-registry"]),
  T("mcp-registry", 4, "MCP Registry", "noun", "em-see-PEE REJ-is-tree",
    "A catalog where MCP servers are published and discovered, letting organizations and tools find available connections rather than building or hunting for them one by one.",
    "She checked the registry first and found an existing MCP server for the platform, saving the team a build.", ["mcp-server", "mcp-gateway"]),
  T("mcp-gateway", 4, "MCP Gateway", "noun", "em-see-PEE GAYT-way",
    "A centralized control point that sits between AI models and many MCP servers, enforcing authentication, permissions, logging, and security policy in one place instead of per connection.",
    "Every agent connection routes through the MCP gateway, so security reviews one chokepoint instead of forty integrations.", ["mcp-server", "guardrails"]),
  T("skills", 4, "Skills", "noun", "skilz",
    "Packaged, reusable instructions and resources (procedures, templates, examples, scripts) that an AI agent can load on demand to perform a specialized task well. Where MCP connects agents to systems, skills equip them with expertise.",
    "The finance team wrote a reporting skill once, and now every agent produces quarterly summaries in the approved format.", ["agent", "mcp"]),

  T("bias", 5, "Bias (in AI)", "noun", "BY-us",
    "Systematic unfairness in a model's outputs, usually inherited from patterns in its training data or design choices. Bias can disadvantage groups of people in hiring, lending, and service decisions, which is why AI systems require testing, not trust.",
    "The screening tool showed bias against nontraditional resumes, so it was pulled for retraining and review.", ["training-data", "governance", "red-teaming"]),
  T("guardrails", 5, "Guardrails", "noun", "GARD-raylz",
    "Technical and policy controls that constrain what an AI system will do: topics it declines, actions it cannot take, content filters, and human approval requirements. Guardrails are designed defenses, and like all defenses, they require testing.",
    "The deployment includes guardrails that block financial advice and route legal questions to counsel.", ["jailbreak", "hitl", "system-prompt"]),
  T("injection", 5, "Prompt Injection", "noun", "prahmpt in-JEK-shun",
    "An attack where malicious instructions are hidden inside content an AI processes (an email, a webpage, a document), tricking the system into following the attacker's commands instead of the user's. The signature security vulnerability of the AI era.",
    "The email contained a prompt injection instructing the assistant to forward the inbox; the gateway's filters caught it.", ["jailbreak", "red-teaming", "mcp-gateway"]),
  T("jailbreak", 5, "Jailbreak", "noun, verb", "JAYL-brayk",
    "A technique for manipulating an AI model into bypassing its own guardrails, typically through cleverly constructed prompts. Distinct from prompt injection: jailbreaking targets the model's rules, injection hijacks it through third-party content.",
    "The red team documented three jailbreaks that got the model to produce prohibited content, all patched before launch.", ["guardrails", "injection", "red-teaming"]),
  T("red-teaming", 5, "Red Teaming", "noun, verb", "RED TEE-ming",
    "Systematically attacking your own AI system before deployment to find failures, vulnerabilities, and harmful behaviors: attempting jailbreaks, injections, and misuse scenarios so adversaries do not find them first.",
    "Red teaming is a launch requirement here; no AI system ships until someone has seriously tried to break it.", ["jailbreak", "injection", "governance"]),
  T("deepfake", 5, "Deepfake / Synthetic Media", "noun", "DEEP-fayk",
    "AI-generated audio, video, or images that convincingly depict real people saying or doing things they never did. A security and media-literacy concern for everyone, not just AI users: voice cloning and fabricated video are now cheap enough to power fraud, impersonation, and disinformation at scale.",
    "The finance team added callback verification after a deepfake of the director's voice nearly authorized a wire transfer.", ["synthetic-data", "genai"]),
  T("alignment", 5, "Model Alignment", "noun", "MAH-dul uh-LYN-ment",
    "The degree to which a model's behavior matches human intentions and values: helpful, honest, and harmless rather than merely capable. Alignment is both a training discipline and an open research problem, and the reason capability alone does not equal trustworthiness.",
    "The review asks two separate questions: is the model capable enough, and is its alignment strong enough for this use case?", ["rlhf", "governance"]),
  T("interpretability", 5, "Interpretability / Explainability (XAI)", "noun", "in-tur-prih-tuh-BIL-ih-tee",
    "The ability to understand why a model produced a given output. Modern models are largely black boxes, which creates real tension in domains where decisions must be explained to auditors, courts, or the public.",
    "For benefits determinations, explainability is a legal requirement, which ruled out the black-box option entirely.", ["grounding", "governance"]),
  T("hitl", 5, "Human-in-the-Loop (HITL)", "noun", "HYOO-mun in thuh LOOP",
    "A design pattern where a human reviews, approves, or can override AI outputs before they take effect. The standard control for consequential decisions, and the answer to \u201cwhat happens when the model is wrong?\u201d",
    "Denials are never automated; the system drafts a recommendation, and a human in the loop makes the call.", ["guardrails", "agentic", "copilot"]),
  T("drift", 5, "Model Drift", "noun", "MAH-dul drift",
    "Degradation of a model's real-world performance over time as conditions change from what it was trained on: new terminology, new behaviors, new patterns. The reason deployed AI needs ongoing monitoring, not one-time approval.",
    "Accuracy quietly fell eight points over the year; the monitoring dashboard caught the model drift before users did.", ["governance", "benchmark"]),
  T("governance", 5, "AI Governance", "noun", "AY-EYE GUV-er-nens",
    "The full framework of policies, roles, review processes, and controls an organization uses to deploy AI responsibly: who approves what, how risk is assessed, how systems are monitored, and who is accountable when they fail.",
    "The AI governance board reviews every proposed use case against a risk tier before anything touches production.", ["aup", "hitl", "drift"])
];

export default TERMS;
